codecov:
  require_ci_to_pass: true
comment:
  behavior: default
  layout: "diff, flags, files"
coverage:
  precision: 2
  range: "70...80"
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project:
      default:
        base: auto
        branches:
          - ^main$
          - ^v2$
        if_ci_failed: error
        only_pulls: false
        paths:
          - ^internal.*
        target: auto
        threshold: 5%
  ignore:
    - "^docs.*"
    - "**/*_mock.go"
github_checks:
  annotations: true